package utils;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;

import javax.ws.rs.core.MediaType;

import io.mosip.testrig.apirig.utils.*;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.json.JSONArray;
import org.json.JSONObject;
import org.testng.SkipException;

import com.github.javafaker.Faker;

import io.mosip.testrig.apirig.dto.TestCaseDTO;
import io.restassured.response.Response;
import utils.testdatamanager.UINManager;

public class InjiWebUtil extends AdminTestUtil {

	private static final Logger logger = Logger.getLogger(InjiWebUtil.class);
	private static final AdminTestUtil adminTestUtil = new AdminTestUtil();
	private static final Faker faker = new Faker();
	private static String dobForSunBirdR = generateDobForSunBirdR();

	public static void setLogLevel() {
		if (InjiWebConfigManager.IsDebugEnabled())
			logger.setLevel(Level.ALL);
		else
			logger.setLevel(Level.ERROR);
	}

	public static TestCaseDTO isTestCaseValidForTheExecution(TestCaseDTO testCaseDTO) {
		String testCaseName = testCaseDTO.getTestCaseName();
		
		currentTestCaseName = testCaseName; 

		int indexof = testCaseName.indexOf("_");
		String modifiedTestCaseName = testCaseName.substring(indexof + 1);

		addTestCaseDetailsToMap(modifiedTestCaseName, testCaseDTO.getUniqueIdentifier());

		String endpoint = testCaseDTO.getEndPoint();
		String inputJson = testCaseDTO.getInput();

		if (SkipTestCaseHandler.isTestCaseInSkippedList(testCaseName)) {
			throw new SkipException(GlobalConstants.KNOWN_ISSUES);
		}
		return testCaseDTO;
	}

	public static String inputstringKeyWordHandeler(String jsonString, String testCaseName) {

		if (jsonString.contains(GlobalConstants.TIMESTAMP)) {
			jsonString = replaceKeywordWithValue(jsonString, GlobalConstants.TIMESTAMP, generateCurrentUTCTimeStamp());
		}

		if (jsonString.contains("$POLICYNUMBERFORSUNBIRDRC$")) {
			String policyNumberForSunBirdR = generateRandomNumberString(9);
			jsonString = replaceKeywordWithValue(jsonString, "$POLICYNUMBERFORSUNBIRDRC$", policyNumberForSunBirdR);
			adminTestUtil.writeAutoGeneratedId(testCaseName, "POLICY", policyNumberForSunBirdR);
		}

		if (jsonString.contains("$FULLNAMEFORSUNBIRDRC$")) {
			String fullNameForSunBirdR = generateFullNameForSunBirdR();
			jsonString = replaceKeywordWithValue(jsonString, "$FULLNAMEFORSUNBIRDRC$", fullNameForSunBirdR);
			adminTestUtil.writeAutoGeneratedId(testCaseName, "NAME", fullNameForSunBirdR);
		}

		if (jsonString.contains("$DOBFORSUNBIRDRC$")) {
			jsonString = replaceKeywordWithValue(jsonString, "$DOBFORSUNBIRDRC$", dobForSunBirdR);
			adminTestUtil.writeAutoGeneratedId(testCaseName, "DOB", dobForSunBirdR);
		}

		return jsonString;

	}

	public static String generateFullNameForSunBirdR() {
		return faker.name().fullName();
	}

	public static String generateDobForSunBirdR() {
		LocalDate dob = faker.date().birthday().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
		return dob.format(DateTimeFormatter.ISO_LOCAL_DATE);
	}

	private static JSONArray mimotoActuatorResponseArray = null;
	private static final Object ACTUATOR_LOCK = new Object();

	public static String getValueFromMimotoActuator(String section, String key) {
		String url = ApplnURI + ConfigManager.getproperty("actuatorMimotoEndpoint");
		String useOldUrl = System.getenv("useOldContextURL");
		if (useOldUrl != null && !useOldUrl.isBlank() && useOldUrl.equalsIgnoreCase("true")) {
			url = url.replace("/v1/mimoto/", "/residentmobileapp/");
		}
		String actuatorCacheKey = url + section + key;
		String value = actuatorValueCache.get(actuatorCacheKey);
		if (value != null && !value.isEmpty())
			return value;

		try {
			synchronized (ACTUATOR_LOCK) {
				if (mimotoActuatorResponseArray == null) {
					Response response = RestClient.getRequest(url, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON);
					JSONObject responseJson = new JSONObject(response.getBody().asString());
					mimotoActuatorResponseArray = responseJson.getJSONArray("propertySources");
				}
			}
			for (int i = 0, size = mimotoActuatorResponseArray.length(); i < size; i++) {
				JSONObject eachJson = mimotoActuatorResponseArray.getJSONObject(i);
				if (eachJson.get("name").toString().contains(section)) {
					value = eachJson.getJSONObject(GlobalConstants.PROPERTIES).getJSONObject(key)
							.get(GlobalConstants.VALUE).toString();
					break;
				}
			}
			actuatorValueCache.put(actuatorCacheKey, value);
			return value;
		} catch (Exception e) {
			return "";
		}
	}

	public static String getSunbirdBaseURL() {
		return InjiWebUtil.getValueFromMimotoActuator("overrides", "mosip.sunbird.url");
	}

	public static TestCaseDTO changeContextURLByFlag(TestCaseDTO testCaseDTO) {
		if (!(System.getenv("useOldContextURL") == null) && !(System.getenv("useOldContextURL").isBlank())
				&& System.getenv("useOldContextURL").equalsIgnoreCase("true")) {
			if (testCaseDTO.getEndPoint().contains("/v1/mimoto/")) {
				testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("/v1/mimoto/", "/residentmobileapp/"));
			}
			if (testCaseDTO.getInput().contains("/v1/mimoto/")) {
				testCaseDTO.setInput(testCaseDTO.getInput().replace("/v1/mimoto/", "/residentmobileapp/"));
			}
		}

		return testCaseDTO;
	}

	public static String getCredentialConfigKey(String wellKnownUrl) {
		try {
			Response response = RestClient.getRequest(wellKnownUrl, MediaType.APPLICATION_JSON,
					MediaType.APPLICATION_JSON);
			JSONObject json = new JSONObject(response.getBody().asString());
			return json.getJSONObject("credential_configurations_supported").keys().next();
		} catch (Exception e) {
			logger.error("Failed to fetch credential configuration from URL: " + wellKnownUrl, e);
			return "default";
		}
	}

	public static HashMap<String, Integer> getActuatorValues(HashMap<String, String> keyMapping) {
		HashMap<String, Integer> result = new HashMap<>();
		String actuatorUrl = ConfigManager.getproperty("apiInternalEndPoint")
				+ ConfigManager.getproperty("actuatorMimotoEndpoint");
		logger.info("Actuator URL: " + actuatorUrl);
		Response response = RestClient.getRequest(actuatorUrl, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON);
		if (response.getStatusCode() != 200) {
			throw new RuntimeException("Failed to fetch actuator values. HTTP error: " + response.getStatusCode());
		}

		JSONObject root = new JSONObject(response.getBody().asString());

		if (!root.has("propertySources")) {
			throw new RuntimeException("[ERROR] No propertySources found in actuator response!");
		}

		for (Object srcObj : root.getJSONArray("propertySources")) {
			if (!(srcObj instanceof JSONObject))
				continue;

			JSONObject src = (JSONObject) srcObj;
			JSONObject props = src.optJSONObject("properties");
			if (props == null)
				continue;

			for (String actuatorKey : keyMapping.keySet()) {
				String resultKey = keyMapping.get(actuatorKey);

				if (!result.containsKey(resultKey) && props.has(actuatorKey)) {
					String rawValue = props.getJSONObject(actuatorKey).optString("value", "0");

					try {
						int intValue = Integer.parseInt(rawValue.trim());
						result.put(resultKey, intValue);
					} catch (NumberFormatException e) {
						System.err
								.println("[WARN] Failed to parse value for key " + actuatorKey + " (" + rawValue + ")");
					}
				}
			}
			if (result.size() == keyMapping.size()) {
				logger.info("All keys mapped successfully");
				break;
			}
		}
		if (result.isEmpty()) {
			logger.info("No actuator values matched the provided key mapping.\"");
		}

		return result;
	}

	public String getOtp(String email, String phone) {
		String channelConfig = InjiWebConfigManager.getproperty("mockNotificationChannel");

		if (channelConfig == null || channelConfig.isBlank()) {
			throw new IllegalArgumentException("mockNotificationChannel is not configured");
		}

		String channel = channelConfig.toLowerCase();

		// Preference order: email > phone
		if (channel.contains("email")) {
			return NotificationListener.getOtp(email);
		} else if (channel.contains("phone")) {
			return NotificationListener.getOtp(phone);
		} else {
			throw new IllegalArgumentException("Unknown OTP channel: " + channelConfig);
		}
	}

	public String uinGetOtp() {
		return getOtp(UINManager.getEmail(), UINManager.getPhone());
	}

}
