package utils.testdatamanager;

import models.Uin;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

import static io.mosip.testrig.apirig.utils.AdminTestUtil.autoGeneratedIDValueCache;

public class UINManager {

    private static final Logger logger = LoggerFactory.getLogger(UINManager.class);

    // Thread-safe pool of available UINs (uin + phone + email)
    private static final BlockingQueue<Uin> availableUINs = new LinkedBlockingQueue<>();

    // Tracks which UIN (and its phone/email) the current thread is holding
    private static final ThreadLocal<Uin> currentThreadUIN = new ThreadLocal<>();

    static {
        int totalUINs = 3;
        for (int i = 1; i <= totalUINs; i++) {
            String prefix = "AddIdentity_withValidParameters_smoke_UIN" + i + "_Pos_";
            availableUINs.add(new Uin(
                    autoGeneratedIDValueCache.get(prefix + "UIN"),
                    autoGeneratedIDValueCache.get(prefix + "PHONE"),
                    autoGeneratedIDValueCache.get(prefix + "EMAIL")
            ));
        }
    }

    //Sample data, data can be passed in this way as well
//    static {
//        availableUINs.add(new Uin("6379306910", "3602485447", "Mimoto_AddIdentity_withValidParameters_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("2038930429", "+4317909080", "Mimoto_AddIdentity_Binding_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("3985781534", "1048876755", "Mimoto_AddIdentity_downloadIssuerCredential_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("4517095619", "2002563005", "Mimoto_AddIdentity_downloadIssuerCredentialWithGoogleLogin_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("4527046734", "8548612682", "Mimoto_AddIdentity_withValidParameters_smoke_Pos_0cb_@mosip.net"));
//    }

    /**
     * Non-blocking acquisition. Returns null immediately if no UIN is free,
     * so the calling thread is never stalled and can move on to other work.
     * The acquired UIN (uin + phone + email) is bound to the current thread
     * via ThreadLocal and can be retrieved with {@link #getCurrentUIN()}.
     */
    public static Uin tryAcquireUIN() {
        Uin uin = availableUINs.poll();
        if (uin != null) {
            currentThreadUIN.set(uin);
            logger.info("[Thread '{}'] Acquired UIN: {}", Thread.currentThread().getName(), uin.getUin());
        } else {
            logger.warn("[Thread '{}'] No UIN available in pool – all are in use", Thread.currentThread().getName());
        }
        return uin;
    }

    /**
     * Returns the UIN (including phone and email) currently held by the calling thread.
     * Returns null if no UIN was acquired on this thread.
     */
    public static Uin getCurrentUIN() {
        return currentThreadUIN.get();
    }

    /** Convenience — returns the UIN string for the current thread's acquired UIN. */
    public static String getUin() {
        Uin uin = currentThreadUIN.get();
        return uin != null ? uin.getUin() : null;
    }

    /** Convenience — returns the phone for the current thread's acquired UIN. */
    public static String getPhone() {
        Uin uin = currentThreadUIN.get();
        return uin != null ? uin.getPhone() : null;
    }

    /** Convenience — returns the email for the current thread's acquired UIN. */
    public static String getEmail() {
        Uin uin = currentThreadUIN.get();
        return uin != null ? uin.getEmail() : null;
    }

    /**
     * Releases the UIN held by the current thread back to the pool.
     * Safe to call even when no UIN was acquired – it is a no-op in that case.
     */
    public static void releaseCurrentThreadUIN() {
        Uin uin = currentThreadUIN.get();
        if (uin != null) {
            availableUINs.offer(uin);
            currentThreadUIN.remove();
            logger.info("[Thread '{}'] Released UIN: {}", Thread.currentThread().getName(), uin.getUin());
        }
    }

    /**
     * Blocking poll used by {@code UINRetryAnalyzer}: waits up to {@code timeout} for any UIN
     * to be released back to the pool. Returns null on timeout.
     * The caller must put the UIN back via {@link #offerUIN(Uin)} so {@link #tryAcquireUIN()}
     * can pick it up in the retried scenario's {@code @Before} hook.
     */
    public static Uin waitForUIN(long timeout, java.util.concurrent.TimeUnit unit)
            throws InterruptedException {
        return availableUINs.poll(timeout, unit);
    }

    /**
     * Returns a UIN directly to the pool without touching the ThreadLocal.
     * Used by {@code UINRetryAnalyzer} to put a peeked UIN back before the retry runs.
     */
    public static void offerUIN(Uin uin) {
        if (uin != null) {
            availableUINs.offer(uin);
        }
    }
}
